language: node_js
before_script:
- pip install --user awscli
- npm install -g gatsby-cli
node_js:
- '10'
deploy:
  provider: script
  script: sh deploy.sh slidesome-beta E1CQWHJ6UTR39N
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: VkZUDvDxPLif/BuyMpw/QDhFI6WcgWBLDUf8tHTSZvSSNX01/cFLrYj4S7QXnke5fSef3DcPkjGVe5IIlHXyfRsxRlw1N9Wuu0iNaxuZW0ROKlGPBTWJlI4U/fd2bwc9Ygh4N3y2SomQ2S7TjJmPVcUqHziXBCNe3xvXb7K1Ncfm9Gz7nxtTdTHbro8bAzDNt5IJ0de4zQXC9vATS28jRLPxj8/0Jh7hy9aBBSPUqwJJrAqt+JKfXRvC6i2fMYfxkx53PTSg3lZq9H+HhokgiDUbGXWxQfcsYbVACCNiGo6hePiFdRM4UU5301mLPF9J3/GinW1VGDAiBs8+HgRtdyOALzIGOO/J8gSHTHY7kl8f8Pi1LVC6w6w/QTNNh1BIBCU6V2OElhOgDdTh79AGcsVbpMSN6kryNVh7zjwitVnU8jL7IH/Vqxe61BL0ZsO35d4OH61pCVA5XmwMrePZK0r2x9uIeisbgAYU5sHtBQATjNLUkW6SZokI4LVRbsIXs/2XX7d+qmSQUh2zyFCi38gcStxUozAYiSNwKF0dKWKmCzgSZvZsiN01ODrqFp42i24abUFkERiAcajVu8gQ6LmMvQD7hjq4TXxaW7w0EAtnutIMK4i+k1JX4yuqw+Kp9DyYwRAzpH6+A5NdcWOaMMA8LUzFiUyG6z3NCCJSiXQ=
  - secure: k0O1ln9HOm2rp78YaQdBOWBUtqoLTcGZ620xGPduiwBpZM5OyT4wkuk3kg2f/RtR5NdEHisA3o5RaqJU7ttXGP8VEi9xOhbNyfYOElWVJxEF6Se7jPbJiTS2/LFdENXyUR02M+BCOUWMzRPmiwTJuH2vqa8XMBVxuMW2T4egzKrr5BFlgP9awSiqtX0dTi+YzqGESqjD1mHGDQUIVIPu1hqkAtTKOyRTqzZNIyEga6XlAxc5Z0JA64MzaC1GEicsZYDzpjrYZpeJstcIMURAryzGg8AH/1/cjyeNc1f+DgzV2D2b/uhABPjFxDFkeY5VbbMjZPXFbw7SEuRJuk2Y6y9XGixyA6iKxcccGbS/IkYaLr3kBCud7YR3HtyRUtq8ujGwtQb23/BpS2Rard7R5No1qNuQ/OH18Qt7ZTDzXFS2OMzWHiipKEpvk0ZkwRm8Oo6z+L/QQxe1gevpWmfDbcx0wWr/ug52aRCD4ne4FsVfryqK8rlIAySywMOqGtBJCJwa4zkRDeVWYGQ9RNx2XWDAfja3qt0OjmO7D/jg44/XqRl730/6K/ecTzEarvCj7K24YFvQByL/ykcuyqtxDHnf50VzkSUn0tGPtloALoI5f0sILZxrL2TjIOXPGDg7oqd9EFzVUdCr6OEQ8PBotYdNRJzkYCLAqNJwxZqplDE=
