language: node_js
before_script:
- pip install --user awscli
- npm install -g gatsby-cli
node_js:
- '10'
deploy:
  provider: script
  script: sh deploy.sh slidesome-beta E1CQWHJ6UTR39N
  skip_cleanup: true
  on:
    branch: master
